language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt --use-mirrors"
before_script:
  - psql -c 'create database rapper_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres -d rapper_test
  
services:
  - mongodb
